In [ ]:
!pip install Tensorflow==2.0b

In [5]:
import tensorflow as tf
import keras
import numpy as np
from keras.layers import Dense 

In [3]:
model = keras.Sequential()

In [7]:
model.add(Dense(units = 1 , input_shape = [1]))

In [9]:
model.compile(optimizer = 'sgd'  , loss = 'mean_squared_error')

In [13]:
xs = np.array([-1.0 , 0 , 1.0 , 2.0 , 3.0 ,4.0])
ys = np.array([-3.0 , -1.0 , 1.0 , 3.0 , 5.0 ,7.0])

In [23]:
model.fit(xs , ys , epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 16ms/step - loss: 2.8008e-07
Epoch 2/100
1/1 [==============================] - 0s 12ms/step - loss: 2.7427e-07
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 2.6869e-07
Epoch 4/100
1/1 [==============================] - 0s 16ms/step - loss: 2.6320e-07
Epoch 5/100
1/1 [==============================] - 0s 16ms/step - loss: 2.5780e-07
Epoch 6/100
1/1 [==============================] - 0s 16ms/step - loss: 2.5245e-07
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 2.4728e-07
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 2.4219e-07
Epoch 9/100
1/1 [==============================] - 0s 16ms/step - loss: 2.3722e-07
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 2.3234e-07
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 2.2761e-07
Epoch 12/100
1/1 [==============================] - 0s 8ms/step - loss: 2.2287e-07
Epoc

1/1 [==============================] - 0s 16ms/step - loss: 3.7442e-08
Epoch 99/100
1/1 [==============================] - 0s 4ms/step - loss: 3.6655e-08
Epoch 100/100
1/1 [==============================] - 0s 16ms/step - loss: 3.5926e-08


In [24]:
model.predict([10.0])

array([[18.999445]], dtype=float32)

In [25]:
#### with different input

In [26]:
xs = np.array([-1.0 , 0 , 1.0 ])
ys = np.array([-3.0 , -1.0 , 1.0 ])

In [28]:
model2 = keras.Sequential([keras.layers.Dense(units = 1 , input_shape = [1])])

In [31]:
model2.compile(optimizer = 'sgd' , loss = 'mean_squared_error')

In [32]:
model2.fit(xs , ys , epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 686ms/step - loss: 6.8592
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 6.6644
Epoch 3/500
1/1 [==============================] - 0s 24ms/step - loss: 6.4753
Epoch 4/500
1/1 [==============================] - 0s 17ms/step - loss: 6.2917
Epoch 5/500
1/1 [==============================] - 0s 8ms/step - loss: 6.1134
Epoch 6/500
1/1 [==============================] - 0s 8ms/step - loss: 5.9403
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: 5.7722
Epoch 8/500
1/1 [==============================] - 0s 22ms/step - loss: 5.6090
Epoch 9/500
1/1 [==============================] - 0s 12ms/step - loss: 5.4506
Epoch 10/500
1/1 [==============================] - 0s 17ms/step - loss: 5.2967
Epoch 11/500
1/1 [==============================] - ETA: 0s - loss: 5.147 - 0s 15ms/step - loss: 5.1473
Epoch 12/500
1/1 [==============================] - 0s 23ms/step - loss: 5.0022
Epoch 13/500
1/1 [==========

1/1 [==============================] - 0s 6ms/step - loss: 0.4062
Epoch 103/500
1/1 [==============================] - 0s 16ms/step - loss: 0.3952
Epoch 104/500
1/1 [==============================] - 0s 18ms/step - loss: 0.3845
Epoch 105/500
1/1 [==============================] - 0s 11ms/step - loss: 0.3741
Epoch 106/500
1/1 [==============================] - 0s 12ms/step - loss: 0.3640
Epoch 107/500
1/1 [==============================] - 0s 22ms/step - loss: 0.3542
Epoch 108/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3446
Epoch 109/500
1/1 [==============================] - ETA: 0s - loss: 0.335 - 0s 13ms/step - loss: 0.3353
Epoch 110/500
1/1 [==============================] - 0s 13ms/step - loss: 0.3263
Epoch 111/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3175
Epoch 112/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3089
Epoch 113/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3006
Epoch 114/500
1/1 [==

1/1 [==============================] - 0s 14ms/step - loss: 0.0269
Epoch 203/500
1/1 [==============================] - 0s 16ms/step - loss: 0.0261
Epoch 204/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0255
Epoch 205/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0248
Epoch 206/500
1/1 [==============================] - 0s 15ms/step - loss: 0.0241
Epoch 207/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0235
Epoch 208/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0228
Epoch 209/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0222
Epoch 210/500
1/1 [==============================] - 0s 23ms/step - loss: 0.0216
Epoch 211/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0211
Epoch 212/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0205
Epoch 213/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0200
Epoch 214/500
1/1 [===========================

1/1 [==============================] - 0s 14ms/step - loss: 0.0018
Epoch 304/500
1/1 [==============================] - 0s 18ms/step - loss: 0.0017
Epoch 305/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0017
Epoch 306/500
1/1 [==============================] - 0s 21ms/step - loss: 0.0016
Epoch 307/500
1/1 [==============================] - 0s 28ms/step - loss: 0.0016
Epoch 308/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0015
Epoch 309/500
1/1 [==============================] - 0s 24ms/step - loss: 0.0015
Epoch 310/500
1/1 [==============================] - 0s 18ms/step - loss: 0.0015
Epoch 311/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0014
Epoch 312/500
1/1 [==============================] - 0s 15ms/step - loss: 0.0014
Epoch 313/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0014
Epoch 314/500
1/1 [==============================] - 0s 20ms/step - loss: 0.0013
Epoch 315/500
1/1 [========================

1/1 [==============================] - 0s 11ms/step - loss: 1.3423e-04
Epoch 400/500
1/1 [==============================] - 0s 8ms/step - loss: 1.3068e-04
Epoch 401/500
1/1 [==============================] - ETA: 0s - loss: 1.2722e-0 - 0s 8ms/step - loss: 1.2722e-04
Epoch 402/500
1/1 [==============================] - 0s 8ms/step - loss: 1.2385e-04
Epoch 403/500
1/1 [==============================] - 0s 7ms/step - loss: 1.2056e-04
Epoch 404/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1737e-04
Epoch 405/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1426e-04
Epoch 406/500
1/1 [==============================] - 0s 8ms/step - loss: 1.1123e-04
Epoch 407/500
1/1 [==============================] - 0s 8ms/step - loss: 1.0828e-04
Epoch 408/500
1/1 [==============================] - 0s 8ms/step - loss: 1.0541e-04
Epoch 409/500
1/1 [==============================] - 0s 8ms/step - loss: 1.0262e-04
Epoch 410/500
1/1 [==============================] - 0s 24ms/

1/1 [==============================] - 0s 8ms/step - loss: 1.0194e-05
Epoch 496/500
1/1 [==============================] - 0s 8ms/step - loss: 9.9248e-06
Epoch 497/500
1/1 [==============================] - 0s 16ms/step - loss: 9.6615e-06
Epoch 498/500
1/1 [==============================] - 0s 13ms/step - loss: 9.4052e-06
Epoch 499/500
1/1 [==============================] - 0s 10ms/step - loss: 9.1565e-06
Epoch 500/500
1/1 [==============================] - 0s 16ms/step - loss: 8.9139e-06


In [33]:
model2.predict([10.0])

array([[18.963966]], dtype=float32)

In [34]:
####less input and less epochs

In [42]:
model3 = keras.Sequential(keras.layers.Dense(units = 1 , input_shape=[1]))
model3.compile(optimizer = 'sgd' , loss = 'mean_squared_error')

In [43]:
xs = np.array([-1.0 , 0 , 1.0 , 2.0 , 3.0 , 4.0, 5.0 , 6.0 , 7.0 , 8.0 , 9.0 , 10.0 , 11.0 , 12.0 , 13.0])
ys = np.array([-3.0 , -1.0 , 1.0 , 3.0 , 5.0 , 7.0 , 9.0 , 11.0 ,13.0 , 15.0 , 17.0 , 19.0 , 21.0 ,23.0 , 25.0])

In [44]:
model3.fit( xs , ys , epochs = 500)

Epoch 1/500
1/1 [==============================] - 1s 699ms/step - loss: 6.7719
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 0.4353
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3585
Epoch 4/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3529
Epoch 5/500
1/1 [==============================] - 0s 24ms/step - loss: 0.3481
Epoch 6/500
1/1 [==============================] - 0s 18ms/step - loss: 0.3434
Epoch 7/500
1/1 [==============================] - 0s 16ms/step - loss: 0.3388
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3342
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3297
Epoch 10/500
1/1 [==============================] - 0s 16ms/step - loss: 0.3253
Epoch 11/500
1/1 [==============================] - 0s 8ms/step - loss: 0.3209
Epoch 12/500
1/1 [==============================] - 0s 16ms/step - loss: 0.3166
Epoch 13/500
1/1 [==============================] - 0s

1/1 [==============================] - 0s 0s/step - loss: 0.0923
Epoch 104/500
1/1 [==============================] - 0s 20ms/step - loss: 0.0911
Epoch 105/500
1/1 [==============================] - 0s 2ms/step - loss: 0.0899
Epoch 106/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0887
Epoch 107/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0875
Epoch 108/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0863
Epoch 109/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0851
Epoch 110/500
1/1 [==============================] - 0s 17ms/step - loss: 0.0840
Epoch 111/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0829
Epoch 112/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0817
Epoch 113/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0806
Epoch 114/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0796
Epoch 115/500
1/1 [==============================] - 

1/1 [==============================] - 0s 4ms/step - loss: 0.0235
Epoch 205/500
1/1 [==============================] - 0s 16ms/step - loss: 0.0232
Epoch 206/500
1/1 [==============================] - 0s 16ms/step - loss: 0.0229
Epoch 207/500
1/1 [==============================] - 0s 16ms/step - loss: 0.0226
Epoch 208/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0223
Epoch 209/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0220
Epoch 210/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0217
Epoch 211/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0214
Epoch 212/500
1/1 [==============================] - 0s 16ms/step - loss: 0.0211
Epoch 213/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0208
Epoch 214/500
1/1 [==============================] - 0s 16ms/step - loss: 0.0205
Epoch 215/500
1/1 [==============================] - ETA: 0s - loss: 0.020 - 0s 0s/step - loss: 0.0203
Epoch 216/500
1/1 [=======

1/1 [==============================] - 0s 9ms/step - loss: 0.0060
Epoch 306/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0059
Epoch 307/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0058
Epoch 308/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0058
Epoch 309/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0057
Epoch 310/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0056
Epoch 311/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0055
Epoch 312/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0054
Epoch 313/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0054
Epoch 314/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0053
Epoch 315/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0052
Epoch 316/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0052
Epoch 317/500
1/1 [==============================] -

1/1 [==============================] - 0s 6ms/step - loss: 0.0015
Epoch 407/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0015
Epoch 408/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0015
Epoch 409/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0015
Epoch 410/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0014
Epoch 411/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0014
Epoch 412/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0014
Epoch 413/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0014
Epoch 414/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0014
Epoch 415/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0014
Epoch 416/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0013
Epoch 417/500
1/1 [==============================] - 0s 17ms/step - loss: 0.0013
Epoch 418/500
1/1 [==============================

In [49]:
model.predict([10.0])[0]

array([18.99982], dtype=float32)

In [51]:
model4 = keras.Sequential(keras.layers.Dense(units = 2 , input_shape=[1]))
model4.add(keras.layers.Dense(units = 1 ))
model4.compile(optimizer = 'sgd' , loss = 'mean_squared_error')

In [52]:
model4.fit( xs , ys , epochs = 500)
model4.predict([11.0])

Epoch 1/500
1/1 [==============================] - 1s 986ms/step - loss: 59.2493
Epoch 2/500
1/1 [==============================] - 0s 8ms/step - loss: 244.6574
Epoch 3/500
1/1 [==============================] - 0s 16ms/step - loss: 1419.0560
Epoch 4/500
1/1 [==============================] - 0s 20ms/step - loss: 1169059.2500
Epoch 5/500
1/1 [==============================] - 0s 16ms/step - loss: 784022724673536.0000
Epoch 6/500
1/1 [==============================] - 0s 16ms/step - loss: inf
Epoch 7/500
1/1 [==============================] - 0s 36ms/step - loss: inf
Epoch 8/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 9/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 10/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 11/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 12/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 13/500
1/1 [============================

1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 107/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 108/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 109/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 110/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 111/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 112/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 113/500
1/1 [==============================] - 0s 17ms/step - loss: nan
Epoch 114/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 115/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 116/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 117/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 118/500
1/1 [==============================] - 0s 22ms/step - loss: nan
Epoch 119

1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 213/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 214/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 215/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 216/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 217/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 218/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 219/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 220/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 221/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 222/500
1/1 [==============================] - 0s 2ms/step - loss: nan
Epoch 223/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 224/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 225/5

1/1 [==============================] - 0s 12ms/step - loss: nan
Epoch 317/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 318/500
1/1 [==============================] - 0s 7ms/step - loss: nan
Epoch 319/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 320/500
1/1 [==============================] - 0s 17ms/step - loss: nan
Epoch 321/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 322/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 323/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 324/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 325/500
1/1 [==============================] - 0s 13ms/step - loss: nan
Epoch 326/500
1/1 [==============================] - 0s 14ms/step - loss: nan
Epoch 327/500
1/1 [==============================] - 0s 12ms/step - loss: nan
Epoch 328/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epo

1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 422/500
1/1 [==============================] - 0s 0s/step - loss: nan
Epoch 423/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 424/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 425/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 426/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 427/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 428/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 429/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 430/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 431/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 432/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 433/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 434/

array([[nan]], dtype=float32)

In [54]:
model4 = keras.Sequential([keras.layers.Dense(units = 1 , input_shape=[1])])
model4.add(keras.layers.Dense(units = 1 ))
model4.compile(optimizer = 'sgd' , loss = 'mean_squared_error')
model4.fit( xs , ys , epochs = 500)
model4.predict([11.0])

Epoch 1/500
1/1 [==============================] - 1s 771ms/step - loss: 25.7701
Epoch 2/500
1/1 [==============================] - 0s 12ms/step - loss: 215.4268
Epoch 3/500
1/1 [==============================] - 0s 16ms/step - loss: 654.3838
Epoch 4/500
1/1 [==============================] - 0s 16ms/step - loss: 86220.6953
Epoch 5/500
1/1 [==============================] - 0s 17ms/step - loss: 313894174720.0000
Epoch 6/500
1/1 [==============================] - 0s 16ms/step - loss: 15149100220475342002668429115392.0000
Epoch 7/500
1/1 [==============================] - 0s 8ms/step - loss: inf
Epoch 8/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 9/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 11/500
1/1 [==============================] - 0s 34ms/step - loss: nan
Epoch 12/500
1/1 [==============================] - 0s 3ms/step - loss: nan
Epoch 13/500
1/1 [

1/1 [==============================] - 0s 5ms/step - loss: nan
Epoch 107/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 108/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 109/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 110/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 111/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 112/500
1/1 [==============================] - 0s 11ms/step - loss: nan
Epoch 113/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 114/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 115/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 116/500
1/1 [==============================] - 0s 23ms/step - loss: nan
Epoch 117/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 118/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoc

1/1 [==============================] - 0s 7ms/step - loss: nan
Epoch 212/500
1/1 [==============================] - 0s 6ms/step - loss: nan
Epoch 213/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 214/500
1/1 [==============================] - 0s 6ms/step - loss: nan
Epoch 215/500
1/1 [==============================] - 0s 6ms/step - loss: nan
Epoch 216/500
1/1 [==============================] - 0s 13ms/step - loss: nan
Epoch 217/500
1/1 [==============================] - 0s 7ms/step - loss: nan
Epoch 218/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 219/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 220/500
1/1 [==============================] - 0s 11ms/step - loss: nan
Epoch 221/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 222/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 223/500
1/1 [==============================] - 0s 11ms/step - loss: nan
Epoch 2

1/1 [==============================] - 0s 7ms/step - loss: nan
Epoch 317/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 318/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 319/500
1/1 [==============================] - 0s 14ms/step - loss: nan
Epoch 320/500
1/1 [==============================] - 0s 6ms/step - loss: nan
Epoch 321/500
1/1 [==============================] - 0s 6ms/step - loss: nan
Epoch 322/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 323/500
1/1 [==============================] - 0s 7ms/step - loss: nan
Epoch 324/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 325/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 326/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 327/500
1/1 [==============================] - 0s 10ms/step - loss: nan
Epoch 328/500
1/1 [==============================] - 0s 9ms/step - loss: nan
Epoch 329

1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 423/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 424/500
1/1 [==============================] - 0s 13ms/step - loss: nan
Epoch 425/500
1/1 [==============================] - 0s 11ms/step - loss: nan
Epoch 426/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 427/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 428/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 429/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 430/500
1/1 [==============================] - 0s 16ms/step - loss: nan
Epoch 431/500
1/1 [==============================] - 0s 19ms/step - loss: nan
Epoch 432/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 433/500
1/1 [==============================] - 0s 8ms/step - loss: nan
Epoch 434/500
1/1 [==============================] - 0s 0s/step - loss: nan
Epoch 435

array([[nan]], dtype=float32)